
<%@ taglib uri="/struts-tags" prefix="s"%>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="css/bootstrap.css" rel="stylesheet">

<link rel="stylesheet" href="css/font-awesome.min.css"/>
<link rel="stylesheet" href="js/layer/skin/layer.css"/>

<script src="js/jquery-1.11.3.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/icetea.js"></script>
<script src="js/layer/layer.js"></script>